name: CI devops 2023

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-backend:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build and test with Maven
        run: |
          cd ./simple-api/ 
          mvn clean install
          cd ../
         
  

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-22.04

    steps:

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v2.5.0


      - name: Build and push simple-api Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api
          file: ./simple-api/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push database Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./database
          file: ./database/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push http-server Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./http-server
          file: ./http-server/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/http-server:latest
          push: ${{ github.ref == 'refs/heads/main' }}
          
